ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM vprix/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/vprix-user
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########


COPY src/ubuntu/install/vscode $INST_SCRIPTS/vscode/
COPY src/ubuntu/install/vscode/vscode.svg /usr/share/icons/hicolor/apps/
RUN bash $INST_SCRIPTS/vscode/install_vs_code.sh  && rm -rf $INST_SCRIPTS/vscode/


# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN apt-get remove -y xfce4-panel

# 设置默认启动脚本
COPY src/ubuntu/install/vscode/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh


######### End Customizations ###########

RUN chown 1000:0 $HOME

ENV HOME /home/vprix-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
